### ISSUE TITLE
[Feature]: Add ability to set "recursive" cli param in config file

### ISSUE THREAD

**Issue by vyahello** [myint/rstcheck#106]
### To Dos

- [X] I have checked the [issues](https://github.com/myint/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Description

Currently, there is no way to set `--recursive` param in config file.

It would be great to set it in the config file like:
```ini
[rstcheck]
recursive=true
```

### Operating System

macOS

### Python Version

Python 3.8.13

### rstcheck Version

5.0.0

**Comment by weibullguy** [comment]
This was also discussed in https://github.com/myint/rstcheck/pull/84#discussion_r853535000 and https://github.com/myint/rstcheck/pull/84#discussion_r854251361

**Comment by Cielquan** [comment]
https://github.com/myint/rstcheck/issues/105#issuecomment-1122656644 also partially applies here:

> First off the code base currently is being reworked (https://github.com/myint/rstcheck/issues/104) and any feature request will have to wait until it is finished.

> But the behavior you are describing is still present.

___

This feature won't be added without #105, as it IMHO does not make sense elsewise. Like describe in the links shared by @weibullguy. Thanks @weibullguy for the linking.

**Comment by Cielquan** [comment]
I will close the issue. If you want to further discuss this topic feel free to reopen it.
