### ISSUE TITLE
[Bug]: Error: No such option: --report Did you mean --report-level?

### ISSUE THREAD

**Issue by peterjc** [myint/rstcheck#110]
### To Dos

- [X] I tested with the [latest released version](https://github.com/myint/rstcheck/releases/latest).

- [X] I have checked the [issues](https://github.com/myint/rstcheck/issues) and think that this is not a duplicate.

- [X] I added a very descriptive title to this issue.

### Example Code (rst)

```rst
N/A
```

### Relevant log output

```Shell
Error: No such option: --report Did you mean --report-level?
```

### Description

Updated rstcheck

### Operating System

Linux, macOS

### Python Version

3.8.5 etc

### rstcheck Version

v6.0.0alpha1

### Additional Context

Older versions of rstcheck like v3.3.1 or v5.0.0 have the following option:

```
  --report level        report system messages at or higher than level; info, warning,
                        error, severe, none
                        (default: info)
```

In v6.0.0alpha1 this has changed, quoting the documentation:

```
--report-level LEVEL         The report level of the linting issues found.
                            Valid levels are: INFO | WARNING | ERROR |
                            SEVERE | NONE. Defauls to INFO. Can be set in
                            config file.
```

This change is breaking me pre-commit configuration when attempting to update rstcheck:

```
    rev: v5.0.0
    hooks:
    -   id: rstcheck
        args: [
            --report=warning,
        ]
```

Is this command line API breakage deliberate? If so, it is an easy but not backward compatible change to make when calling rstcheck.

P.S. Note typo "Defauls" here and in the source code.

**Comment by DanielNoord** [comment]
It is noted in the `BREAKING CHANGES` section for the new version: https://github.com/myint/rstcheck#id37

So I think this is deliberate and you should probably update your configuration. We did the same for `pylint`.

**Comment by peterjc** [comment]
You're probably right, but I think that notice could be more explicit then, I took this to be config file specific:

``Renamed config report to report_level (#100)``

How about this?:

``Renamed renamed config file and command line switch report to report_level (#100)``

**Comment by DanielNoord** [comment]
> Actually, it just needs a new entry like:
> 
> `Renamed CLI option --ignore-language to --ignore-languages (#100)`
> 
> i.e. add:
> 
> `Renamed CLI option --report to --report-level (#100)`

That seems like it follows the general pattern of the README. I'd say open a PR for it, I think it would be appreciated by the maintainer who seems to have been doing a lot of work recently for this project (which isn't their own).

**Comment by Cielquan** [comment]
Yes the change is deliberate.
I am doing a big rework and making some options more clear is one part of this.
