### ISSUE TITLE
Include MIT/Expat license text

### ISSUE THREAD

**Issue by fladi** [myint/rstcheck#14]
It would be nice to include the [MIT/Expat](http://opensource.org/licenses/MIT) license text (also in MANIFEST.in). This is a prerequisite for Debian packaging.

**Comment by myint** [comment]
Sure. Currently the license text is only in the [header of `rstcheck.py`](https://github.com/myint/rstcheck/blob/dd7e2692818c40714fb2871b7d2fc461bb872ef1/rstcheck.py#L3). I'll gladly accept a pull request to make it compliant with Debian packaging.

Thanks
