### ISSUE TITLE
sphinx unknown directive "Highlight"

### ISSUE THREAD

**Issue by hredestig** [myint/rstcheck#21]
same as #1 , rstcheck failing this:

```
.. Highlight:: shell

============
Contributing
============
```
with 
```
rstcheck --report 2 *.rst
CONTRIBUTING.rst:1: (ERROR/3) Unknown directive type "Highlight".
(pyv35-lite) ➜  cobrapy git:(feat/ravn-mat) 
```
perhaps one could have some --ignore-directives flag to auto drop all these..

**Comment by myint** [comment]
Try installing Sphinx >= 1.5.

https://github.com/myint/rstcheck#sphinx

**Comment by hredestig** [comment]
thanks, that works well
