### ISSUE TITLE
Allow config in a setup.cfg file

### ISSUE THREAD

**Issue by 73VW** [myint/rstcheck#37]
Programs like `pydocstyle` or `flake8` allow users to put their configs in the same file called `setup.cfg`.
Because I am often working with those and rstcheck, I am a bit annoyed about having to write my config to a special file only for rstcheck.

Would it be possible to have a such an option? If so I'd like to try to submit patches to provide this feature.

setup.cfg example
```cfg
[pycodestyle]
exclude = ...
[pydocstyle]
match-dir = ...
[flake8]
exclude = ...
jobs = ...
# It would be nice to also have:
[rstcheck]
#Your configs here
```

**Comment by myint** [comment]
Sounds good to me!
