### ISSUE TITLE
If no specific file/files are mentioned in the args, check all `.rst` files recursively

### ISSUE THREAD

**Issue by 5j9** [myint/rstcheck#40]
I find it tedious to use [``find``](http://man7.org/linux/man-pages/man1/find.1.html) to search for all `.rst` files and pass them to ``rstcheck``.  I think it would be nice if ``rstcheck`` could check all `.rst` files in the current working directory and sub-directorates recursively. Or perhaps do that if the argument is a directory, accepting relative paths (e.g. ``rstcheck .``).

**Comment by myint** [comment]
Please test out #41.

Thanks
