### ISSUE TITLE
Ignore specific errors

### ISSUE THREAD

**Issue by stsewd** [myint/rstcheck#42]
Hi, is possible to do this?

Sometimes there is some false positives errors that I would like to suppress. 

I would glad to help if this is possible :)

**Comment by myint** [comment]
I think this is good idea! I would welcome any help in this.

It looks like [`docutils` doesn't categorize](https://github.com/docutils-mirror/docutils/blob/e88c5fb08d5cdfa8b4ac1020dd6f7177778d5990/docutils/nodes.py#L1371-L1373) their warning/error messages beyond the high-level categories of `info`, `warning`, `error`, and `severe`.

So we may need to filter them out at a textual level. *Maybe we could accept a command-line option like `--ignore-messages` that would take a regex as input (`--ignore-messages='(Title underline too short.*|Duplicate implicit target.*'`).*

This could be done in the code below.

https://github.com/myint/rstcheck/blob/1b0c09f6ae05dfc34f597f6ea37e97cc4afab08d/rstcheck.py#L197-L203

For context, note that `string_io` contains the `docutils` messages:

https://github.com/myint/rstcheck/blob/1b0c09f6ae05dfc34f597f6ea37e97cc4afab08d/rstcheck.py#L178-L183
