### ISSUE TITLE
Add tests to source tarball

### ISSUE THREAD

**Issue by jayvdb** [myint/rstcheck#53]
I'd like to submit this linter to packaging systems, and have a working .spec at

https://build.opensuse.org/package/view_file/home:jayvdb:coala:python3-bears/python-rstcheck/python-rstcheck.spec?expand=1

Source tarballs helps achieve this without hacks like downloading the tests from github.

**Comment by polyzen** [comment]
Already done, just hasn't been released yet:
https://github.com/myint/rstcheck/blob/master/MANIFEST.in#L8

**Comment by jayvdb** [comment]
https://github.com/myint/rstcheck/pull/52#issuecomment-463077918
