### ISSUE TITLE
openSUSE 42.3 and 15.1 failures

### ISSUE THREAD

**Issue by jayvdb** [myint/rstcheck#54]
Interesting little test failures, which do not occur on the latest rolling release of openSUSE "tumbleweed" (using python3.7), but are occurring on the current releases (using python3.4 and python3.6).

My guess is that this is related to the python version, but that seems surprising as they are quite mature versions of the older releases.

15.1(python3.6.5)
```console
[  107s] + python3 ./rstcheck.py --ignore-language=cpp examples/bad/bad_cpp.rst
[  109s] + python3 ./rstcheck.py -
[  110s] 'utf-8' codec can't encode characters in position 2-29: surrogates not allowed
[  110s] ++ echo -e '\x1b[01;31mFailed\x1b[0m'
[  110s] [01;31mFailed[0m
[  110s] error: Bad exit status from /var/tmp/rpm-tmp.eEw9bE (%check)
```
42.3(python3.4.6)
```console
[  108s] + python3 ./rstcheck.py --ignore-language=cpp examples/bad/bad_cpp.rst
[  109s] + python3 ./rstcheck.py -
[  110s] 'ascii' codec can't decode byte 0xc2 in position 1850: ordinal not in range(128)
[  110s] ++ echo -e '\x1b[01;31mFailed\x1b[0m'
[  110s] [01;31mFailed[0m
[  110s] error: Bad exit status from /var/tmp/rpm-tmp.FIRbSf (%check)
```

**Comment by jayvdb** [comment]
Live logs at https://build.opensuse.org/package/show/home:jayvdb:coala:python3-bears/python-rstcheck

**Comment by jayvdb** [comment]
If it is an error in the filename itself, it might be related to https://build.opensuse.org/package/live_build_log/home:jayvdb:coala:python3-bears/python-dennis/openSUSE_Leap_15.1/x86_64

**Comment by Cielquan** [comment]
Both mentioned python versions are EOL and no longer supported since rstcheck version 4.0.
