### ISSUE TITLE
Add support for Sphinx>2.0

### ISSUE THREAD

**Issue by thedrow** [myint/rstcheck#58]
Right now we only test < 2.0.

**Comment by samccann** [comment]
Is there any guidance available for how to move this issue along? I'm wondering if it's as simple as a PR to add a couple of lines here:
https://github.com/myint/rstcheck/blob/master/.travis.yml#L13
for Sphinx 2.0, 2.1, etc?  

(I'm guessing it's not that easy but figured I'd ask just in case :-)

**Comment by polyzen** [comment]
Just to clarify, this seems to only apply to the Travis testing. rstcheck seems to work fine still with Sphinx 2.4.4.

**Comment by Cielquan** [comment]
@polyzen is correct. There was never an upper constraint to the sphinx version. Only sphinx <1.5 is not supported.

I also added tests with each major sphinx version since 1.5 -- see `tox.ini`
