### ISSUE TITLE
--ignore-messages option blocks following errors

### ISSUE THREAD

**Issue by Rom888** [myint/rstcheck#60]
--ignore-messages option stops showing other errors if they are after ignored message.

For this example::

title1
======

references
----------

title2
======

references
----------

title3
===

rstcheck rstcheck_issue.rst
output: rstcheck_issue.rst:11: (INFO/1) Duplicate implicit target name: "references".

rstcheck --ignore-messages "(Duplicate implicit target name:.*)" rstcheck_issue.rst
output: nothing

But we have another error in the text: "Possible title underline, too short for the title3.", and if we fix "Duplicate implicit target name: "references"." we will see it:
rstcheck --ignore-messages "(Duplicate implicit target name:.*)" rstcheck_issue.rst
output: rstcheck_issue.rst:14: (INFO/1) Possible title underline, too short for the title.

**Comment by myint** [comment]
This seems like an issue in the lower-level `docutils` library rather than something we can control at the `rstcheck` level.

**Comment by polyzen** [comment]
Is this something that has-been/should-be reported upstream?

**Comment by tdegeus** [comment]
Same here! Is there a workaround for this?

**Comment by Cielquan** [comment]
I think this is strongly related to #83.

I guess rstcheck only outputs the first encountered error on each file and because it found an error it does not continue on that file. I guess the silencing of the error happens later on.

**Comment by Cielquan** [comment]
This is fixed by #83.
