### ISSUE TITLE
Upgrade Sphinx version

### ISSUE THREAD

**Issue by Zethson** [myint/rstcheck#64]
rstcheck requires Sphinx 1.4.9.
There is already Sphinx 2.4.4 now. I cannot include rstcheck into my package, since it conflicts with the Sphinx version.

**Comment by stsewd** [comment]
> rstcheck requires Sphinx 1.4.9.

Where did you read that? I have tested with sphinx 1.8 without any problems. Haven't tested it with 2.x

**Comment by Zethson** [comment]
pip told me that when I tried to install the package.
It wanted to override my existing Sphinx installation with the old one.

**Comment by stsewd** [comment]
Maybe you are installing an old version, sphinx isn't listed as requirement anymore

https://github.com/myint/rstcheck/pull/20

**Comment by Zethson** [comment]
Interesting. I'll see why pip was trying to install an old version.
