### ISSUE TITLE
Make Sphinx ignores configurable

### ISSUE THREAD

**Issue by peterjc** [myint/rstcheck#65]
Currently ``rstcheck`` is hard coded to ignore Sphinx RST extensions via:

https://github.com/myint/rstcheck/blob/v3.3.1/rstcheck.py#L163

If sphinx is installed, it get the current information, otherwise defaults to a hard coded list of roles and directives. This makes sense as a default behaviour.

However, not everyone uses Sphinx, and in that case it would be useful to be able to disable this (and get linting messages about undefined roles and directives).

**Comment by stsewd** [comment]
Maybe we could have an option like `--ignore-sphinx` or `--no-sphinx` and `--sphinx`. With those flags we could decide if sphinx integrations should be forced or ignored, if the user doesn't pass any flag rtscheck uses sphinx if it's installed to keep backwards compatibility.

**Comment by peterjc** [comment]
Yes, that's what I was thinking too. I like ``--no-sphinx`` or ``--ignore-sphinx`` more than ``--sphinx`` as the setting name given it is a negative option.

**Comment by Cielquan** [comment]
Because version 4.0 was just released I think version 5.0 would be ok to release soon too.

Therefore I think adding a out-in flag "--use-sphinx-defaults" or smth like this would be a good idea. So the default behavior would be:
- to ignore sphinx stuff if the flag is not set and sphinx is not installed
- use those default values if the flag is set and sphinx is not installed
- use sphinx if sphinx is installed

Would you try and implement that feature?

**Comment by peterjc** [comment]
I'd like this functionality for use via Python for https://github.com/peterjc/flake8-rst-docstrings/pull/23 but am unlikely to work on this in the short term. Perhaps later, especially if the functionality that enables (https://github.com/peterjc/flake8-rst-docstrings/issues/22 i.e. linting code samples within Python docstrings) becomes directly important in my day job.

**Comment by Cielquan** [comment]
At first I added the option to use default values but later into the coding I came to the realization that no defaults are IMHO the better option. Reason behind it is, that those would have to be maintained as well and are not in our control.

Therefore sphinx support only with sphinx installed. I think this is ok.

**Comment by peterjc** [comment]
I'm happy with making the Sphinx directives and roles opt-in, especially as you're warning about this change so clearly in the README file as a future breaking change. Thank you!
