### ISSUE TITLE
[feature] Add --pypi-strict option

### ISSUE THREAD

**Issue by pandafy** [myint/rstcheck#72]
It will be helpful to add a `pypi-strict` option. `rstcheck` is perfect for my usecase but due to absence of strictness towards PyPI syntax I had to introduce quite a few modifications from other modules. 

@myint  I am happy to extend my help in adding this feature if it looks great.

**Comment by Cielquan** [comment]
This sounds like a good idea. But I think this feature would be out of scope for this repo.

But it may be a good thing to add via a plugin system which is requested in #80.
