### ISSUE TITLE
[Feature] Support pyproject.toml as config file

### ISSUE THREAD

**Issue by Cielquan** [myint/rstcheck#74]
Like the headline says I would like to have `rstcheck` support `pyproject.toml` as a config-file.

One could add `pyproject.toml` to the default file list which gets automatically checked when `--config` is not given. BUT then one have to add a toml lib like `tomlkit` to the dependencies. Or one makes it optional as an extra and then you have to specify the config-file via `--config`. I like the first one better.

I took a look at the source and think that the implementation for parsing the toml-file should not be that hard, especially because the config as ini has no complex constructs: only str und list.

I would also provide a PR but before I start the work I would like to have the maintainers thought to not work for the bin.

**Comment by stsewd** [comment]
as for the additional dependency (actually I think python should include one in the std since is being used widely now...) an `extras_require` key in the setup.py file could be used. `pip install "rstcheck[toml-config]"` or similar.

**Comment by Cielquan** [comment]
I totally agree with python adding a toml lib to their stdlib, but I think this will take some time. Also `toml` is not 1.0 yet, but close with 1.0rc3. For the flake8 maintainer e.g. this is a requirement before adding pyproject.toml support to flake8. But I personally do not share this thought.

**Comment by Cielquan** [comment]
To update this:
I will also wait till a new release is made: https://github.com/myint/rstcheck/issues/69
As a new release would show that there is the possibility for new releases.

---

We had the issue with [myint/eradicate](https://github.com/myint/eradicate) as Steven is unfortunately not that active here anymore. He will have his reasons.
I and @sobolevn contacted him (via email) and @sobolevn (owner of [`flake8-eradicate`](https://github.com/wemake-services/flake8-eradicate)) got permissions for the repo and PyPI package to publish new releases: [link to PR leading to this](https://github.com/myint/eradicate/pull/27)
Maybe an active Contributor may ask him for permissions for `rstcheck` too.
