### ISSUE TITLE
Links with bracket references cause unexpected "Hyperlink target is not referenced" error

### ISSUE THREAD

**Issue by jessebrennan** [myint/rstcheck#77]
Put the following in a minimal rst file:

```
`a link <different name_>`_

.. _different name: https//www.example.com
```

running rstcheck minimal.rst gives:
```
minimal.rst:1: (INFO/1) Hyperlink target "a link" is not referenced.
```

Even though, as far as I can tell, this should be perfectly valid rst.

**Comment by Cielquan** [comment]
I can reproduce this issue.

Do you want to try and fix it?

**Comment by jessebrennan** [comment]
This isn't a priority for me, unfortunately so I don't want to spend the time on a fix. Out of curiosity I tried searching the error message and nothing came up, so I wouldn't even know where to start without a lot of study of the code.

**Comment by Cielquan** [comment]
Okay. I learned after writing here, that all messages actually come from docutils. So this may be an upstream issue all along.

**Comment by Cielquan** [comment]
Note: I think this may also be related to #19.

**Comment by Cielquan** [comment]
I looked into the matter and this is an issue with docutils and not rstcheck. rstcheck simply passes the info message on.

If you open an issue over at https://sourceforge.net/p/docutils/_list/tickets please link it here, so we can follow the progress.

**Comment by jessebrennan** [comment]
I tried to reproduce this with docutils and was unable to. At least under normal operating conditions, docutils can handle this kind of link. I suspect it has something to do with the way rstcheck uses docutils, but I don't have the time to dig in and create a simpler reproduction.

All that's to say that I'm not yet convinced this is an upstream issue.

**Comment by Cielquan** [comment]
I have no issue reproducing with docutils.

1. I cloned the docutils repo:
```shell
$ git clone git://repo.or.cz/docutils.git
```

2. I create the test file `test.rst` based on your example:
```rst
`a link <different name_>`_

.. _different name: https//www.example.com
```

3. And then I call and get (while a venv is active where docutils is installed):
```shell
$ ./docutils/docutils/tools/docutils-cli.py test.rst --report=1 > /dev/null
test.rst:1: (INFO/1) Hyperlink target "a link" is not referenced.
```

I redirect the output to `/dev/null` to avoid the resulting chunk HTML being printed to the console too.

I hope this proofs my statement.

**Comment by jessebrennan** [comment]
Ah yes, `--report=1` is the key I was missing. Thanks for your reproduction. I've opened an issue with docutils https://sourceforge.net/p/docutils/bugs/446/

**Comment by AA-Turner** [comment]
Cross-posting from bug-446:

It is technically correct output, although I agree surprising.

There are two targets in this document, `different name` and `a link`. 

`different name` is referenced by the alias reference syntax in line 1, but `a link` is never referenced.

The following document generates no errors:
```restructuredtext
`a link <different name_>`_

reference to `a link`_

.. _different name: https://www.example.com
```

Alternatively, you could use an anonymous reference:
```restructuredtext
`a link <different name_>`__

.. _different name: https://www.example.com
```

Perhaps we could improve the error message?

A

**Comment by jessebrennan** [comment]
@Cielquan it sounds like this issue is invalid. If anyone in the future gets confused by this as I did, @AA-Turner's comment should clear things up. Also the documentation [here](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#hyperlink-references) and [here](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#anonymous-hyperlinks).
