### ISSUE TITLE
Detect more than one error

### ISSUE THREAD

**Issue by kreuzberger** [myint/rstcheck#83]
Hi!
I wanted to use rstcheck to get warnings in my rst files, but rstcheck currently returns only the first found error, does not try to process the whole document. Is this intended or a misconfiguration?

 
\*******
Chapter
\*******

Section
\====

.. code:: 

The example should return 2 errors (1. underline to short, 2. missing content-block)

**Comment by Cielquan** [comment]
I can reproduce the issue on CLI and as plugin in VSCode.

**Comment by Cielquan** [comment]
I figured it out. There was an option I set in the closing commit to not halt on an error.
